Added new styles and fixed bugs
QAB-LABS/QAB-HUB pull request #30
Opened 2019-10-17 23:43 UTC by bobbypwang

2019-10-17 23:49 UTC, AndresMWeber requested changes

2019-10-17 23:49 UTC, AndresMWeber commented on server/package.json
> +        "bcrypt": "^3.0.6",
uninstall and fix

2019-10-17 23:49 UTC, AndresMWeber commented on client/package.json
> +    "@babel/helper-regex": "^7.5.5"
Remove this please

2019-10-17 23:49 UTC, AndresMWeber commented on .gitignore
> +/client/client.zip
Fix this to 

*.zip

2019-10-18 03:13 UTC, Kiwi-x-Kiwi approved these changes

2019-10-18 03:24 UTC, merged